excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - ${PWD}/Pods
  - Source/ExcludedFolder
  - Source/ExcludedFile.swift
  - Source/*/ExcludedFile.swift # Exclude files with a wildcard

disabled_rules: # rule identifiers to exclude from running
    - trailing_whitespace
    - force_cast
    - force_try
    - empty_enum_arguments
    - multiple_closures_with_trailing_closure
    - line_length
    - identifier_name
